PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT ?this
WHERE {
  {
    SELECT ?this
    WHERE {
      [] crm:P7_took_place_at ?this
      FILTER(REGEX(STR(?this), "^https://sws.geonames.org/\\d+/$"))
    }
  }
}
GROUP BY ?this
LIMIT ?_limit
OFFSET ?_offset
