name: Create graph

# Run every 3 hours. Don't run it more often; otherwise you might hit
# GeoNames' hourly and daily request limits - http://www.geonames.org/export/
on:
  schedule:
    - cron: "0 */3 * * *"

# on:
#   push:
#     branches: ["main"]

# Run a single workflow at a time
concurrency:
  group: ${{ github.workflow }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data repository
        uses: actions/checkout@v4
        with:
          path: ./data
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          path: ./code
          repository: sdevalk/cc-integration-v2
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install app
        run: |
          cd ./code
          npm ci
          npx turbo run build --filter=@colonial-collections/graph-create-geonames
      - name: Create or update a graph
        run: |
          cd ./data
          mkdir -p "$RUNNER_TEMP"
          test -f ./queues/locations.tar.gz && tar -xzf ./queues/locations.tar.gz -C "$RUNNER_TEMP"
          test -f ./queues/countries.tar.gz && tar -xzf ./queues/countries.tar.gz -C "$RUNNER_TEMP"
          ../code/apps/graph-create-geonames/dist/cli.js create \
            --resource-dir ./resources \
            --queue-dir "$RUNNER_TEMP" \
            --endpoint-url "https://api.colonialcollections.nl/datasets/data-hub/knowledge-graph/services/kg/sparql" \
            --locations-iterate-query-file ./queries/iterate-locations.rq \
            --countries-iterate-query-file ./queries/iterate-countries.rq \
            --triplydb-instance-url "${{ vars.TRIPLYDB_INSTANCE_URL }}" \
            --triplydb-api-token "${{ secrets.TRIPLYDB_API_TOKEN }}" \
            --triplydb-account "${{ vars.TRIPLYDB_ACCOUNT }}" \
            --triplydb-dataset "${{ vars.TRIPLYDB_DATASET_KG }}" \
            --triplydb-service-name kg \
            --triplydb-service-type virtuoso \
            --graph-name "https://data.colonialcollections.nl/geonames" \
            --temp-dir "$RUNNER_TEMP"
      - name: Save changes
        run: |
          cd ./data
          mkdir -p ./queues
          test -f "$RUNNER_TEMP/locations.sqlite" && tar -czf ./queues/locations.tar.gz -C "$RUNNER_TEMP" locations.sqlite
          test -f "$RUNNER_TEMP/countries.sqlite" && tar -czf ./queues/countries.tar.gz -C "$RUNNER_TEMP" countries.sqlite
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --quiet -a -m "Save changes" || true
          git push --force -u origin
